# Generated by Django 5.0.4 on 2024-05-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'تامین کننده', 'verbose_name_plural': 'تامین کننده ها'},
        ),
    ]
