# Generated by Django 5.0.4 on 2024-05-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_phonenumber_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
    ]
